### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by cinghialino** [jamrizzi/easyappointments-docker#1]
"unable to connect to your database server using the provided settings
Filename: controllers/Appointments.php
Line Number: 28"

I have only changed the db name from "root" to something else..

I have put the new database username in the environment settings in the docker, but I can't get past that error.

any suggestion please?

**Comment by clayrisser** [comment]
Thanks for filing this issue. I'll look into it for sure.

**Comment by clayrisser** [comment]
The db name isn't 'root' by default. It's 'easyappointments'. It's the default database username that is 'root' by default. I just tried to reproduce this, and I verfied that it's setting up the easyappointments config properly when you pass in the environment variables. That means it's either an incorrect database setup, or a bug in easyappointments. You can try and file a bug on their repo at https://github.com/alextselegidis/easyappointments/issues.

Before you file a bug on their repo, confirm that your config.php file is setup properly when you pass in the env's. You can do this by sshing into the running Docker container.

```sh
docker exec -it my-running-container /bin/sh
```
