### ISSUE TITLE
can you update it?

### ISSUE THREAD

**Issue by cinghialino** [jamrizzi/easyappointments-docker#3]
thanks

**Comment by clayrisser** [comment]
Can you be more specific?

**Comment by cinghialino** [comment]
Hi Jamrizzi, 

version 1.3.0 is out, and this seems outdated. 
I really appreciated to find a docker version of this! thanks

**Comment by clayrisser** [comment]
I will try and update it soon. If you need it super urgently, feel free to create a pull request.

**Comment by cinghialino** [comment]
i'd just like to try this software. wouldn't know how to do a pull request. I appreciate your efforts.

**Comment by clayrisser** [comment]
Ok, no prob. I'll make sure I update it.

**Comment by clayrisser** [comment]
It's updated. I also added tags so the older version is still supported.

**Comment by clayrisser** [comment]
The following commit updated it.
a96f81f17102dc4619a260b5c6828db904fcb275

**Comment by cinghialino** [comment]
thnk you so much!

unfortunately it doesn't work for me. for some reason there is an overlay on the install page and even if I remove it from the page it won't allow to proceed.

thanks anyway.

**Comment by clayrisser** [comment]
Hmm, maybe there is an issue with their version 3. I'm not sure. I'll look into it more later.

**Comment by cinghialino** [comment]
nah, it was the same on the previous version. that's when I decided to ask about an update. the overlay is in fact a broken "loading" gif. Since it's coming up as a broken link (source is `http://localhost:8888/assets/img/loading.gif`), and the installation redirect that always points to localhost - even when you change your base url, I am assuming there is something that gets in the way.

**Comment by clayrisser** [comment]
Ok, I'll let you know when it's fixed.
